In [11]:

import pandas as pd     
import numpy as np      
import matplotlib.pyplot as plt  
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import pandas as pd
from sklearn.model_selection import GridSearchCV

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
import seaborn as sns

In [2]:

McReg = pd.read_csv("mergedMc.csv") 
McReg.head(500)

,StudyNum,Date,ORG.1,Pseudomonas,Specimen,Ciprofloxacin,Ceftazidime,Meropenem,PipTazo,Tob,...,CHRYB,ABCO,EICO,ACURS,HSD,ASPER,MYAB,CALU,HAPAPH,STAN
0,1,08/01/2013,Pseudomona,1,"C,13.0140319.DA",1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,08/01/2013,Pseudomona,1,"C,13.0140319.DA",1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,08/01/2013,Pseudomona,1,"C,13.0140319.DA",0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,12/01/2013,Pseudomona,1,"C,13.0140518.VA",1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,12/01/2013,Pseudomona,1,"C,13.0140518.VA",1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,10,06/02/2017,Pseudomona,1,"C,17.0142707.WA",0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
496,10,20/02/2017,Pseudomona,1,"C,17.0143365.XA",0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
497,10,06/03/2017,Pseudomona,1,"C,17.0144713.YA",0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
498,10,06/03/2017,Pseudomona,1,"C,17.0144713.YA",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
499,10,20/03/2017,Pseudomona,1,"C,17.0145657.QA",0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
McReg = McReg.drop(['StudyNum', 'Date', 'ORG.1', 'Specimen'], axis=1)

print(McReg.dtypes)

Pseudomonas      int64
Ciprofloxacin    int64
Ceftazidime      int64
Meropenem        int64
PipTazo          int64
                 ...
ASPER            int64
MYAB             int64
CALU             int64
HAPAPH           int64
STAN             int64
Length: 148, dtype: object

In [4]:
print(McReg.columns)

Index(['Pseudomonas', 'Ciprofloxacin', 'Ceftazidime', 'Meropenem', 'PipTazo',
       'Tob', 'MDR', 'PYOMO', 'YEASTS', 'PYOS',
       ...
       'CHRYB', 'ABCO', 'EICO', 'ACURS', 'HSD', 'ASPER', 'MYAB', 'CALU',
       'HAPAPH', 'STAN'],
      dtype='object', length=148)

In [5]:

X = McReg.drop('MDR', axis=1)
y = McReg['MDR']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
param_grid = {
    'n_estimators': [200, 300, 400],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt']
}

In [19]:

rf = RandomForestClassifier(random_state=42)

grid_search = GridSearchCV(rf, param_grid, cv=5)
grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
best_score = grid_search.best_score_

test_score = grid_search.score(X_test, y_test)

print("Best Parameters:", best_params)
print("Best Score:", best_score)
print("Test Score:", test_score)

Best Parameters: {'max_depth': None, 'max_features': 'auto', 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 200}
Best Score: 0.9977344968096118
Test Score: 0.9993527508090615

Accuracy: 1.0